[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
neptune = "9xa8bCxxeeuVM953qj2zHQ2LLqF6YZPKo3Kmrk4HfXzS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.apr.dev"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
